import subprocess

def apply_service_tweak(service_name, startup_type):
    """Apply a startup type tweak to a Windows service."""
    try:
        subprocess.run(
            ["sc", "config", service_name, f"start={startup_type}"],
            capture_output=True, text=True, check=True
        )
        print(f"[OK] {service_name}: set startup -> {startup_type}")
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] {service_name}: failed -> {e.stderr.strip()}")


if __name__ == "__main__":
    tweaks = [
        # 🚫 Disabled services
        ("AJRouter", "disabled"),
        ("AppVClient", "disabled"),
        ("DiagTrack", "disabled"),
        ("DialogBlockingService", "disabled"),
        ("NetTcpPortSharing", "disabled"),
        ("RemoteAccess", "disabled"),
        ("RemoteRegistry", "disabled"),
        ("UevAgentService", "disabled"),
        ("shpamsvc", "disabled"),
        ("ssh-agent", "disabled"),
        ("tzautoupdate", "disabled"),
        ("uhssvc", "disabled"),

        # 🕒 Delayed-auto services
        ("BITS", "delayed-auto"),
        ("DoSvc", "delayed-auto"),
        ("MapsBroker", "delayed-auto"),
        ("WSearch", "delayed-auto"),
        ("sppsvc", "delayed-auto"),
        ("wscsvc", "delayed-auto"),

        # ⚡ Auto services
        ("AudioEndpointBuilder", "auto"),
        ("AudioSrv", "auto"),
        ("Audiosrv", "auto"),
        ("BFE", "auto"),
        ("BthAvctpSvc", "auto"),
        ("BthHFSrv", "auto"),
        ("CoreMessagingRegistrar", "auto"),
        ("CryptSvc", "auto"),
        ("Dhcp", "auto"),
        ("DispBrokerDesktopSvc", "auto"),
        ("Dnscache", "auto"),
        ("DusmSvc", "auto"),
        ("EventLog", "auto"),
        ("EventSystem", "auto"),
        ("FontCache", "auto"),
        ("IKEEXT", "demand"),
        ("KeyIso", "auto"),
        ("LSM", "auto"),
        ("LanmanServer", "auto"),
        ("MpsSvc", "auto"),
        ("OneSyncSvc", "auto"),
        ("Power", "auto"),
        ("ProfSvc", "auto"),
        ("RpcEptMapper", "auto"),
        ("SamSs", "auto"),
        ("Schedule", "auto"),
        ("SENS", "auto"),
        ("SgrmBroker", "auto"),
        ("Spooler", "auto"),
        ("SystemEventsBroker", "auto"),
        ("TermService", "auto"),
        ("TrkWks", "auto"),
        ("VGAuthService", "auto"),
        ("VMTools", "auto"),
        ("VaultSvc", "auto"),
        ("Wcmsvc", "auto"),
        ("WinDefend", "auto"),
        ("WlanSvc", "auto"),
        ("mpssvc", "auto"),
        ("nsi", "auto"),
        ("webthreatdefusersvc", "auto"),

        # 📦 Demand (manual) services
        ("ALG", "demand"),
        ("AppIDSvc", "demand"),
        ("AppMgmt", "demand"),
        ("Appinfo", "demand"),
        ("AssignedAccessManagerSvc", "demand"),
        ("AxInstSV", "demand"),
        ("BDESVC", "demand"),
        ("BTAGService", "demand"),
        ("BcastDVRUserService", "demand"),
        ("BluetoothUserService", "demand"),
        ("Browser", "demand"),
        ("CDPSvc", "demand"),
        ("COMSysApp", "demand"),
        ("CaptureService", "demand"),
        ("CertPropSvc", "demand"),
        ("ConsentUxUserSvc", "demand"),
        ("CredentialEnrollmentManagerUserSvc", "demand"),
        ("CscService", "demand"),
        ("DPS", "auto"),
        ("DcpSvc", "demand"),
        ("DevQueryBroker", "demand"),
        ("DeviceAssociationBrokerSvc", "demand"),
        ("DeviceAssociationService", "demand"),
        ("DeviceInstall", "demand"),
        ("DevicePickerUserSvc", "demand"),
        ("DevicesFlowUserSvc", "demand"),
        ("DsSvc", "demand"),
        ("DsmSvc", "demand"),
        ("EFS", "demand"),
        ("EapHost", "demand"),
        ("EntAppSvc", "demand"),
        ("FDResPub", "demand"),
        ("Fax", "demand"),
        ("FrameServer", "demand"),
        ("FrameServerMonitor", "demand"),
        ("GraphicsPerfSvc", "demand"),
        ("HomeGroupListener", "demand"),
        ("HomeGroupProvider", "demand"),
        ("HvHost", "demand"),
        ("IEEtwCollectorService", "demand"),
        ("InstallService", "demand"),
        ("InventorySvc", "demand"),
        ("IpxlatCfgSvc", "demand"),
        ("KtmRm", "demand"),
        ("LicenseManager", "demand"),
        ("LxpSvc", "demand"),
        ("MSDTC", "demand"),
        ("MSiSCSI", "demand"),
        ("McpManagementService", "demand"),
        ("MessagingService", "demand"),
        ("MicrosoftEdgeElevationService", "demand"),
        ("MixedRealityOpenXRSvc", "demand"),
        ("MsKeyboardFilter", "demand"),
        ("NPSMSvc", "demand"),
        ("NaturalAuthentication", "demand"),
        ("NcaSvc", "demand"),
        ("NcbService", "demand"),
        ("NcdAutoSetup", "demand"),
        ("NetSetupSvc", "demand"),
        ("Netlogon", "demand"),
        ("Netman", "demand"),
        ("NgcCtnrSvc", "demand"),
        ("NgcSvc", "demand"),
        ("NlaSvc", "demand"),
        ("P9RdrService", "demand"),
        ("PNRPAutoReg", "demand"),
        ("PNRPsvc", "demand"),
        ("PcaSvc", "demand"),
        ("PeerDistSvc", "demand"),
        ("PenService", "demand"),
        ("PerfHost", "demand"),
        ("PhoneSvc", "demand"),
        ("PimIndexMaintenanceSvc", "demand"),
        ("PlugPlay", "demand"),
        ("PolicyAgent", "demand"),
        ("PrintNotify", "demand"),
        ("PrintWorkflowUserSvc", "demand"),
        ("PushToInstall", "demand"),
        ("QWAVE", "demand"),
        ("RasAuto", "demand"),
        ("RasMan", "demand"),
        ("RetailDemo", "demand"),
        ("RmSvc", "demand"),
        ("RpcLocator", "demand"),
        ("SCPolicySvc", "demand"),
        ("SCardSvr", "demand"),
        ("SDRSVC", "demand"),
        ("SEMgrSvc", "demand"),
        ("SNMPTRAP", "demand"),
        ("SNMPTrap", "demand"),
        ("SSDPSRV", "demand"),
        ("ScDeviceEnum", "demand"),
        ("SecurityHealthService", "demand"),
        ("Sense", "demand"),
        ("SensorDataService", "demand"),
        ("SensorService", "demand"),
        ("SensrSvc", "demand"),
        ("SessionEnv", "demand"),
        ("SharedAccess", "demand"),
        ("SharedRealitySvc", "demand"),
        ("SmsRouter", "demand"),
        ("SstpSvc", "demand"),
        ("StiSvc", "demand"),
        ("StorSvc", "demand"),
        ("TapiSrv", "demand"),
        ("TieringEngineService", "demand"),
        ("TimeBroker", "demand"),
        ("TimeBrokerSvc", "demand"),
        ("TokenBroker", "demand"),
        ("TroubleshootingSvc", "demand"),
        ("TrustedInstaller", "demand"),
        ("UI0Detect", "demand"),
        ("UmRdpService", "demand"),
        ("UnistoreSvc", "demand"),
        ("VSS", "demand"),
        ("VacSvc", "demand"),
        ("W32Time", "demand"),
        ("WEPHOSTSVC", "demand"),
        ("WFDSConMgrSvc", "demand"),
        ("WMPNetworkSvc", "demand"),
        ("WManSvc", "demand"),
        ("WPDBusEnum", "demand"),
        ("WSService", "demand"),
        ("WalletService", "demand"),
        ("WarpJITSvc", "demand"),
        ("WbioSrvc", "demand"),
        ("WcsPlugInService", "demand"),
        ("WdNisSvc", "demand"),
        ("WdiServiceHost", "demand"),
        ("WdiSystemHost", "demand"),
        ("WebClient", "demand"),
        ("Wecsvc", "demand"),
        ("WerSvc", "demand"),
        ("WiaRpc", "demand"),
        ("WinHttpAutoProxySvc", "demand"),
        ("WinRM", "demand"),
        ("WpcMonSvc", "demand"),
        ("WwanSvc", "demand"),
        ("XblAuthManager", "demand"),
        ("XblGameSave", "demand"),
        ("XboxGipSvc", "demand"),
        ("XboxNetApiSvc", "demand"),
        ("autotimesvc", "demand"),
        ("bthserv", "demand"),
        ("camsvc", "demand"),
        ("cbdhsvc", "demand"),
        ("cloudidsvc", "demand"),
        ("dcsvc", "demand"),
        ("defragsvc", "demand"),
        ("diagnosticshub.standardcollector.service", "demand"),
        ("diagsvc", "demand"),
        ("dmwappushservice", "demand"),
        ("dot3svc", "demand"),
        ("edgeupdate", "demand"),
        ("edgeupdatem", "demand"),
        ("embeddedmode", "demand"),
        ("fdPHost", "demand"),
        ("fhsvc", "demand"),
        ("hidserv", "demand"),
        ("icssvc", "demand"),
        ("lfsvc", "demand"),
        ("lltdsvc", "demand"),
        ("lmhosts", "demand"),
        ("msiserver", "demand"),
        ("netprofm", "demand"),
        ("p2pimsvc", "demand"),
        ("p2psvc", "demand"),
        ("perceptionsimulation", "demand"),
        ("pla", "demand"),
        ("seclogon", "demand"),
        ("smphost", "demand"),
        ("spectrum", "demand"),
        ("svsvc", "demand"),
        ("swprv", "demand"),
        ("upnphost", "demand"),
        ("vds", "demand"),
        ("vm3dservice", "demand"),
        ("vmicguestinterface", "demand"),
        ("vmicheartbeat", "demand"),
        ("vmickvpexchange", "demand"),
        ("vmicrdv", "demand"),
        ("vmicshutdown", "demand"),
        ("vmictimesync", "demand"),
        ("vmicvmsession", "demand"),
        ("vmicvss", "demand"),
        ("vmvss", "demand"),
        ("wbengine", "demand"),
        ("wcncsvc", "demand"),
        ("webthreatdefsvc", "demand"),
        ("wercplsupport", "demand"),
        ("wisvc", "demand"),
        ("wlpasvc", "demand"),
        ("wmiApSrv", "demand"),
        ("workfolderssvc", "demand"),
        ("wudfsvc", "demand"),
    ]

    for service, mode in tweaks:
        apply_service_tweak(service, mode)

    print("\n==============================")
    print("--- Service Tweaks Completed ---")
    print("==============================")
